name: "Test builds"
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  test-build:
    strategy:
      matrix:
        runners:
          - release: stable
          - release: testing
    runs-on: ubuntu-latest
    container:
      image: "docker.io/debian:testing@sha256:942aae6c16e617a949763462ec3b6b5d65e60d90e4cae762bc1bce0522d26fa2"
      options: --privileged
    steps:
      - name: Install relevant tools
        run: apt-get update && apt-get install -y podman mkosi make
        env:
          DEBIAN_FRONTEND: noninteractive
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Build container
        run: make build-${{ matrix.runners.release }}
