name: "Test builds"
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  test-build:
    strategy:
      matrix:
        runners:
          - release: stable
          - release: testing
    runs-on: ubuntu-latest
    container:
      image: "docker.io/debian:testing@sha256:16faa8d1cd99fcb2d30eebe90454e26b20499055fa7094e9b55d32d1a7666f08"
      options: --privileged
    steps:
      - name: Install relevant tools
        run: apt-get update && apt-get install -y podman mkosi make
        env:
          DEBIAN_FRONTEND: noninteractive
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Build container
        run: make build-${{ matrix.runners.release }}
