name: "Test builds"
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  test-build:
    strategy:
      matrix:
        runners:
          - release: stable
          - release: testing
    runs-on: ubuntu-latest
    container:
      image: "docker.io/debian:testing@sha256:d671983fe9e0d185db24542fb93cd9a006fa9d014ae52d6741061b69c8f42be7"
      options: --privileged
    steps:
      - name: Install relevant tools
        run: apt-get update && apt-get install -y podman mkosi make
        env:
          DEBIAN_FRONTEND: noninteractive
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Build container
        run: make build-${{ matrix.runners.release }}
